# namespace-memory-limit.yml

apiVersion: v1
kind: LimitRange
metadata:
  name: memory-limit-range
  namespace: prod
spec:
  limits:
  - default:
      memory: 500Mi
    defaultRequest:
      memory: 250Mi
    type: Container

#
# create namespace first using -
# kubectl create namespace learning
#
# apply it using - 
# kubectl apply -f namespace-memory-limit.yml
# 
# check limits -
# kubectl get limitranges --namespace=prod
#
# get details of limits -
# kubectl describe limitranges memory-limit-range --namespace=prod
# 
# delete the memory limits - 
# kubectl delete limitranges memory-limit-range --namespace=prod
# 
# delete namespace -
# kubectl delete namespace prod
#
