apiVersion: v1
kind: Pod
metadata:
  name: burst
  labels:
    app: apache
spec:
  containers:
    - name: Sanjaya-app
      image: nginx
      resources:
        limits:
          memory: 250Mi
          cpu: 200m
        requests:
          memory: 150Mi
          cpu: 100m
