# pod-simple-with-ports.yml
#
apiVersion: v1
kind: Pod
metadata:
  name: Sanjaya-app
  namespace: prod
  labels:
   app: Sanjaya-app
spec:
  containers:
    - name: web-app
      image: nginx
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
 
#
# Creating a simple pod. Which has apache
# configured inside it. Exposed port is 80 
# using TCP protocol  
#
# create namespace prod -
# kubectl create namespace prod
#
# run the pod
# kubectl create -f pod-simple-with-ports.yml
#
# check the pod
# kubectl get pods --namespace=prod
#
# get details about pod
# kubectl describe pod/Sanjaya-app --namespace=prod
# 
# Find the IP address of this pod and the node where
# its running. Go to that node and do a :
# 
# curl http://ip-address-of-pod
#
# You should the website welcome message from 
# Network Nuts
#
# delete pod
# kubectl delete pod/Sanjay-app --namespace=prod
#
