# deployment-webserver-with-service.yml
# we are deploying a webserver with 2 replicas
# and then exposing the webserver service using
# service resource
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Sanjaya-web
  namespace: prod
spec:
  selector:
    matchLabels:
      run: Sanjaya-web
  replicas: 2
  template:
    metadata:
      labels:
        run: Sanjaya-web
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80


#
# Creating a deployment with two pods and then
# exposing the webserver using service resource type.
#
# create namespace prod -
# kubectl create namespace prod
#
# initialize the deployment
# kubectl create -f deployment-webserver-with-service.yml
#
# check the deployment
# kubectl get deployment --namespace=prod
#
# get more details about the deployment
# kubectl describe deployments Sanjaya-web --namespace=prod
#
# get details about pods initialized by deployment
# kubectl get pods --namespace=prod
#
# get information about all pods created by deployment Sanjaya-web
# kubectl get pods -l run=Sanjaya-web -o wide --namespace=learning
# 
# get the IP address of all pods initialized by deployment nn-web
# kubectl get pods -l run=Sanjaya-web -o yaml --namespace=prod | grep podIP
#
# expose the deployment using service resource
# kubectl expose deployment/Sanjaya-web --namespace=prod
#
# get information about the service (note down the Cluster IP)
# kubectl get service Sanjaya-web --namespace=prod
#
# get detailed information about service, where:
# Endpoints - are the pod's IP address 
# IP - is the service IP address, where we will hit (call it Cluster IP)
# kubectl describe service Sanjaya-web --namespace=prod
#
# check endpoints (the pods which the service will hit) for the service
# kubectl get ep Sanjaya-web --namespace=prod
#
# You can go to ANY node in the cluster and use 
# curl http://CLUSTER-IP
#
# --- You should be able to get the website contents ---
#
# delete the deployment
# kubectl delete deployment Sanjaya-web --namespace=prod
#
# delete the service
# kubectl delete service Sanjaya-web --namespace=prod
#
